## Linear Classifier in TensorFlow 
Using Low Level API in Eager Execution mode

### Load tensorflow

In [0]:
import tensorflow as tf

In [0]:
#Enable Eager Execution if using tensflow version < 2.0
#From tensorflow v2.0 onwards, Eager Execution will be enabled by default

### Collect Data

In [0]:
import pandas as pd

In [204]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [0]:
data = pd.read_csv('/content/drive/My Drive/lab_residency6/prices.csv')

### Check all columns in the dataset

In [206]:
data.columns

Index(['date', 'symbol', 'open', 'close', 'low', 'high', 'volume'], dtype='object')

### Drop columns `date` and  `symbol`

In [0]:
data = data.drop(['date', 'symbol'], axis=1)

In [208]:
data.head()

         open       close         low        high     volume
0  123.430000  125.839996  122.309998  126.250000  2163600.0
1  125.239998  119.980003  119.940002  125.540001  2386400.0
2  116.379997  114.949997  114.930000  119.739998  2489500.0
3  115.480003  116.620003  113.500000  117.440002  2006300.0
4  117.010002  114.970001  114.089996  117.330002  1408600.0

In [209]:
data.shape

(851264, 5)

### Consider only first 1000 rows in the dataset for building feature set and target set
Target 'Volume' has very high values. Divide 'Volume' by 1000,000

In [0]:
data = data.loc[:999, :]

In [0]:
data['volume'] = data['volume']/1000000

In [212]:
data.shape

(1000, 5)

### Divide the data into train and test sets

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X = data[['open', 'close',	'low',	'high']]

In [0]:
y= data['volume']
y=y.astype('float32')

In [0]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=7)

#### Convert Training and Test Data to numpy float32 arrays

In [0]:
x_train=x_train.astype('float32')

In [0]:
x_test=x_test.astype('float32')

### Normalize the data
You can use Normalizer from sklearn.preprocessing

In [0]:
from sklearn import preprocessing

In [0]:
#Input features
x = tf.placeholder(shape=[None,4],dtype=tf.float32, name='x-input')

#Normalize the data
x_n = preprocessing.normalize(x_train)
x_n = x_n.astype('float32')

#Actual Prices
y_ = tf.placeholder(shape=[None],dtype=tf.float32, name='y-input')

## Building the Model in tensorflow

1.Define Weights and Bias, use tf.zeros to initialize weights and Bias

In [0]:
import numpy as np

In [0]:
#W = tf.Variable(tf.zeros(shape=[4,1]), name="Weights")
W = tf.Variable(tf.random_normal([4, 1]), name="Weights")
b = tf.Variable(tf.zeros(shape=[1]),name="Bias")

In [0]:
#We will use normalized data
#y = tf.add(tf.matmul(x,W),b,name='output')
y = tf.add(tf.matmul(x_n,W),b,name='output')

2.Define a function to calculate prediction

In [0]:
loss = tf.reduce_mean(tf.square(y-y_),name='Loss')

3.Loss (Cost) Function [Mean square error]

In [0]:
train_op = tf.train.GradientDescentOptimizer(0.03).minimize(loss)

4.Function to train the Model

1.   Record all the mathematical steps to calculate Loss
2.   Calculate Gradients of Loss w.r.t weights and bias
3.   Update Weights and Bias based on gradients and learning rate to minimize loss

In [0]:
#Lets start graph Execution
sess = tf.Session()

# variables need to be initialized before we can use them
sess.run(tf.global_variables_initializer())

#how many times data need to be shown to model
training_epochs = 100

## Train the model for 100 epochs 
1. Observe the training loss at every iteration
2. Observe Train loss at every 5th iteration

In [228]:
for epoch in range(training_epochs):
            
    #Calculate train_op and loss
    _, train_loss = sess.run([train_op,loss],feed_dict={x:x_train, y_:y_train})
    
    if epoch % 5 == 0:
        print ('Training loss at step: ', epoch, ' is ', train_loss)

Training loss at step:  0  is  301.96658
Training loss at step:  5  is  281.75595
Training loss at step:  10  is  276.12704
Training loss at step:  15  is  274.55936
Training loss at step:  20  is  274.12277
Training loss at step:  25  is  274.00113
Training loss at step:  30  is  273.9673
Training loss at step:  35  is  273.95786
Training loss at step:  40  is  273.9552
Training loss at step:  45  is  273.95447
Training loss at step:  50  is  273.95428
Training loss at step:  55  is  273.95422
Training loss at step:  60  is  273.9542
Training loss at step:  65  is  273.9542
Training loss at step:  70  is  273.95422
Training loss at step:  75  is  273.95422
Training loss at step:  80  is  273.9542
Training loss at step:  85  is  273.95422
Training loss at step:  90  is  273.9542
Training loss at step:  95  is  273.95422

### Get the shapes and values of W and b

In [229]:
W.shape
W

In [230]:
b.shape

TensorShape([Dimension(1)])

### Model Prediction on 1st Examples in Test Dataset

In [0]:
feed_dict = {x: x_test}  
y_pred = y.eval(feed_dict, session=sess)

In [236]:
y_pred

array([[5.6103826],
       [5.607754 ],
       [5.608819 ],
       [5.618808 ],
       [5.616083 ],
       [5.6150465],
       [5.613774 ],
       [5.6032124],
       [5.6149626],
       [5.612602 ],
       [5.6164722],
       [5.6020536],
       [5.614557 ],
       [5.6083384],
       [5.6197023],
       [5.6030836],
       [5.6123414],
       [5.6150866],
       [5.6109657],
       [5.6022654],
       [5.606207 ],
       [5.610275 ],
       [5.6189566],
       [5.6158085],
       [5.599986 ],
       [5.615213 ],
       [5.61309  ],
       [5.6063538],
       [5.6137743],
       [5.6131163],
       [5.609998 ],
       [5.5836544],
       [5.6043935],
       [5.6110606],
       [5.5876923],
       [5.5931168],
       [5.6112003],
       [5.6141014],
       [5.6122665],
       [5.6010303],
       [5.6094027],
       [5.6113577],
       [5.608717 ],
       [5.614362 ],
       [5.6187763],
       [5.596734 ],
       [5.6091537],
       [5.614899 ],
       [5.6033554],
       [5.61644  ],
       [5.6120806],
       [5.616108 ],
       [5.6154375],
       [5.6118765],
       [5.613097 ],
       [5.612149 ],
       [5.614473 ],
       [5.606783 ],
       [5.594187 ],
       [5.6056995],
       [5.612896 ],
       [5.6107244],
       [5.6040063],
       [5.5976896],
       [5.6089354],
       [5.6124606],
       [5.619128 ],
       [5.6016526],
       [5.606045 ],
       [5.6118183],
       [5.6253786],
       [5.6102123],
       [5.615882 ],
       [5.623078 ],
       [5.608468 ],
       [5.6150618],
       [5.6154995],
       [5.6111674],
       [5.6069555],
       [5.607891 ],
       [5.609812 ],
       [5.608898 ],
       [5.6059437],
       [5.6116457],
       [5.614558 ],
       [5.6133823],
       [5.6112127],
       [5.6124573],
       [5.61322  ],
       [5.6161356],
       [5.611086 ],
       [5.6048117],
       [5.621496 ],
       [5.617978 ],
       [5.6029587],
       [5.6082187],
       [5.620222 ],
       [5.60963  ],
       [5.6141977],
       [5.610649 ],
       [5.616394 ],
       [5.611058 ],
       [5.614992 ],
       [5.6119723],
       [5.6169987],
       [5.607809 ],
       [5.59521  ],
       [5.6044645],
       [5.6107597],
       [5.613375 ],
       [5.592436 ],
       [5.614045 ],
       [5.613893 ],
       [5.6081333],
       [5.614315 ],
       [5.6164627],
       [5.610451 ],
       [5.6003356],
       [5.6089478],
       [5.61022  ],
       [5.595293 ],
       [5.6169634],
       [5.586591 ],
       [5.610507 ],
       [5.6099153],
       [5.6128964],
       [5.6052103],
       [5.60713  ],
       [5.609928 ],
       [5.597762 ],
       [5.6173143],
       [5.5996537],
       [5.5966525],
       [5.6112194],
       [5.6128664],
       [5.6126738],
       [5.6075373],
       [5.6125326],
       [5.60783  ],
       [5.6123   ],
       [5.6145473],
       [5.617813 ],
       [5.600672 ],
       [5.6105123],
       [5.6139183],
       [5.604067 ],
       [5.6056547],
       [5.6102047],
       [5.613966 ],
       [5.6097417],
       [5.6085367],
       [5.6185446],
       [5.6119328],
       [5.6147623],
       [5.608903 ],
       [5.6114354],
       [5.613935 ],
       [5.594055 ],
       [5.621485 ],
       [5.5949907],
       [5.6047506],
       [5.618232 ],
       [5.61193  ],
       [5.606498 ],
       [5.6077776],
       [5.6130543],
       [5.605397 ],
       [5.600482 ],
       [5.5982285],
       [5.6081367],
       [5.617159 ],
       [5.6139183],
       [5.6068583],
       [5.617774 ],
       [5.609478 ],
       [5.6173973],
       [5.6170273],
       [5.612544 ],
       [5.6128445],
       [5.6135054],
       [5.608927 ],
       [5.601038 ],
       [5.61658  ],
       [5.613718 ],
       [5.6079993],
       [5.596749 ],
       [5.6151867],
       [5.610295 ],
       [5.607606 ],
       [5.611307 ],
       [5.6035166],
       [5.6123657],
       [5.615101 ],
       [5.610905 ],
       [5.6128893],
       [5.6129804],
       [5.608412 ],
       [5.6189027],
       [5.611539 ],
       [5.613571 ],
       [5.6179504],
       [5.6130257],
       [5.616017 ],
       [5.600753 ],
       [5.612094 ],
       [5.6168127],
       [5.6083164],
       [5.608587 ],
       [5.612289 ],
       [5.613469 ],
       [5.613966 ],
       [5.611069 ],
       [5.6146173],
       [5.6065445],
       [5.615699 ],
       [5.6174374],
       [5.612521 ],
       [5.5996103],
       [5.6158504],
       [5.614599 ],
       [5.6150284],
       [5.6096787],
       [5.624276 ],
       [5.6044374],
       [5.6066837],
       [5.6008043],
       [5.6034102],
       [5.601621 ],
       [5.609641 ],
       [5.6055546],
       [5.6087494],
       [5.61276  ],
       [5.623453 ],
       [5.6198273],
       [5.6066704],
       [5.5951047],
       [5.613082 ],
       [5.609885 ],
       [5.6080675],
       [5.6085362],
       [5.6119294],
       [5.603862 ],
       [5.6095037],
       [5.6105776],
       [5.6015763],
       [5.616353 ],
       [5.6120005],
       [5.61174  ],
       [5.6171865],
       [5.6135206],
       [5.6080112],
       [5.613846 ],
       [5.6107903],
       [5.6204405],
       [5.614469 ],
       [5.614499 ],
       [5.6125593],
       [5.6205597],
       [5.611988 ],
       [5.6208286],
       [5.6112213],
       [5.581869 ],
       [5.613358 ],
       [5.615864 ],
       [5.6096   ],
       [5.6135683],
       [5.595177 ],
       [5.608674 ],
       [5.6130266],
       [5.6149015],
       [5.612631 ],
       [5.612815 ],
       [5.6115723],
       [5.615059 ],
       [5.5988603],
       [5.6176167],
       [5.616395 ],
       [5.6104527],
       [5.61013  ],
       [5.607621 ],
       [5.6122837],
       [5.606839 ],
       [5.6163373],
       [5.6154046],
       [5.615617 ],
       [5.613353 ],
       [5.6130753],
       [5.6009655],
       [5.615178 ],
       [5.6178293],
       [5.614999 ],
       [5.6164885],
       [5.616622 ],
       [5.613247 ],
       [5.6149445],
       [5.6101108],
       [5.623123 ],
       [5.6166425],
       [5.606563 ],
       [5.614497 ],
       [5.6134477],
       [5.607959 ],
       [5.610821 ],
       [5.6210203],
       [5.611122 ],
       [5.61256  ],
       [5.616542 ],
       [5.611561 ],
       [5.613208 ],
       [5.599162 ],
       [5.5979834],
       [5.613348 ],
       [5.6111383],
       [5.614058 ],
       [5.596334 ],
       [5.6095986],
       [5.6020384],
       [5.613179 ],
       [5.6160283],
       [5.6055803],
       [5.606057 ],
       [5.612158 ],
       [5.599614 ],
       [5.613845 ],
       [5.6178694],
       [5.5958843],
       [5.6122003],
       [5.614248 ],
       [5.6124115],
       [5.606037 ],
       [5.614176 ],
       [5.615279 ],
       [5.6196327],
       [5.6109586],
       [5.6058006],
       [5.6143856],
       [5.61819  ],
       [5.620322 ],
       [5.6146045],
       [5.6086054],
       [5.60522  ],
       [5.6109977],
       [5.6080847],
       [5.6164846],
       [5.620934 ],
       [5.602972 ],
       [5.6035833],
       [5.614625 ],
       [5.6016135],
       [5.6190906],
       [5.6168194],
       [5.615595 ],
       [5.5780597],
       [5.6145134],
       [5.603017 ],
       [5.6139717],
       [5.6131115],
       [5.6106887],
       [5.5956583],
       [5.617951 ],
       [5.617769 ],
       [5.625234 ],
       [5.60675  ],
       [5.616238 ],
       [5.6058373],
       [5.6173277],
       [5.618961 ],
       [5.6097727],
       [5.60894  ],
       [5.607891 ],
       [5.610818 ],
       [5.614928 ],
       [5.6128297],
       [5.614542 ],
       [5.604146 ],
       [5.611555 ],
       [5.614053 ],
       [5.598144 ],
       [5.619442 ],
       [5.616804 ],
       [5.6163797],
       [5.616068 ],
       [5.6144657],
       [5.6159115],
       [5.6094565],
       [5.602704 ],
       [5.6126394],
       [5.616289 ],
       [5.62188  ],
       [5.613862 ],
       [5.6144447],
       [5.620824 ],
       [5.6164064],
       [5.621643 ],
       [5.6101346],
       [5.615256 ],
       [5.6189823],
       [5.6042366],
       [5.6119137],
       [5.613953 ],
       [5.6099944],
       [5.611637 ],
       [5.6017036],
       [5.5997076],
       [5.6159067],
       [5.6125097],
       [5.6054773],
       [5.5973973],
       [5.6144223],
       [5.606695 ],
       [5.60658  ],
       [5.6114454],
       [5.613456 ],
       [5.6059885],
       [5.6012206],
       [5.609052 ],
       [5.6193686],
       [5.612345 ],
       [5.6251655],
       [5.6030684],
       [5.5895705],
       [5.6116652],
       [5.6160583],
       [5.60072  ],
       [5.6144037],
       [5.605154 ],
       [5.598282 ],
       [5.6121674],
       [5.602424 ],
       [5.618557 ],
       [5.615805 ],
       [5.5928316],
       [5.6027403],
       [5.610478 ],
       [5.612051 ],
       [5.618269 ],
       [5.6090727],
       [5.6076355],
       [5.610349 ],
       [5.620048 ],
       [5.6081743],
       [5.617387 ],
       [5.6064005],
       [5.608938 ],
       [5.6113815],
       [5.610403 ],
       [5.610978 ],
       [5.6218586],
       [5.614356 ],
       [5.6144724],
       [5.6169643],
       [5.6128297],
       [5.5656967],
       [5.606653 ],
       [5.5840635],
       [5.612031 ],
       [5.603793 ],
       [5.603738 ],
       [5.615019 ],
       [5.6134634],
       [5.6079187],
       [5.6106215],
       [5.617095 ],
       [5.6115885],
       [5.6029015],
       [5.6198406],
       [5.6001463],
       [5.6128798],
       [5.602855 ],
       [5.6138506],
       [5.611573 ],
       [5.603424 ],
       [5.609728 ],
       [5.6195674],
       [5.6218853],
       [5.611947 ],
       [5.6123567],
       [5.6159754],
       [5.6143036],
       [5.6174335],
       [5.602219 ],
       [5.6208153],
       [5.6095214],
       [5.602352 ],
       [5.576088 ],
       [5.616291 ],
       [5.61745  ],
       [5.601189 ],
       [5.6137676],
       [5.5837674],
       [5.6128407],
       [5.6002903],
       [5.6157036],
       [5.609245 ],
       [5.607744 ],
       [5.605893 ],
       [5.616394 ],
       [5.604435 ],
       [5.605297 ],
       [5.6134844],
       [5.577675 ],
       [5.6144896],
       [5.604225 ],
       [5.615399 ],
       [5.607514 ],
       [5.607766 ],
       [5.6153483],
       [5.5867944],
       [5.6126904],
       [5.6090164],
       [5.6090584],
       [5.611339 ],
       [5.5932946],
       [5.6110067],
       [5.6121273],
       [5.6066637],
       [5.619225 ],
       [5.5728073],
       [5.6209164],
       [5.609626 ],
       [5.6176753],
       [5.605542 ],
       [5.6205635],
       [5.6187677],
       [5.613276 ],
       [5.6190047],
       [5.609769 ],
       [5.5936623],
       [5.614957 ],
       [5.5961933],
       [5.610735 ],
       [5.620569 ],
       [5.617671 ],
       [5.6107287],
       [5.6125097],
       [5.6115723],
       [5.614715 ],
       [5.61122  ],
       [5.6163144],
       [5.615896 ],
       [5.612816 ],
       [5.620677 ],
       [5.615703 ],
       [5.6062374],
       [5.61487  ],
       [5.616897 ],
       [5.607959 ],
       [5.6217623],
       [5.610751 ],
       [5.613764 ],
       [5.6076965],
       [5.5988626],
       [5.617746 ],
       [5.6055074],
       [5.615382 ],
       [5.6178665],
       [5.617011 ],
       [5.6112423],
       [5.610935 ],
       [5.6116104],
       [5.609003 ],
       [5.6173124],
       [5.609599 ],
       [5.6141844],
       [5.608246 ],
       [5.6177273],
       [5.5973725],
       [5.6153135],
       [5.622642 ],
       [5.6139207],
       [5.618469 ],
       [5.6144166],
       [5.6064386],
       [5.6171083],
       [5.6130667],
       [5.6113214],
       [5.577486 ],
       [5.606169 ],
       [5.597063 ],
       [5.596648 ],
       [5.618375 ],
       [5.616487 ],
       [5.610043 ],
       [5.614707 ],
       [5.615533 ],
       [5.612364 ],
       [5.617544 ],
       [5.6122103],
       [5.606735 ],
       [5.6120014],
       [5.615602 ],
       [5.6001167],
       [5.6244335],
       [5.6069245],
       [5.6045275],
       [5.612505 ],
       [5.5856423],
       [5.600277 ],
       [5.62317  ],
       [5.6101995],
       [5.6125717],
       [5.6141095],
       [5.6085353],
       [5.616947 ],
       [5.6136255],
       [5.616159 ],
       [5.616427 ],
       [5.6172056],
       [5.617757 ],
       [5.612716 ],
       [5.5964193],
       [5.6106286],
       [5.617614 ],
       [5.617159 ],
       [5.6091275],
       [5.583032 ],
       [5.5938807],
       [5.589937 ],
       [5.6038237],
       [5.609739 ],
       [5.6120586],
       [5.6161623],
       [5.615138 ],
       [5.617278 ],
       [5.6104608],
       [5.611258 ],
       [5.5749817],
       [5.607809 ],
       [5.6127396],
       [5.595474 ],
       [5.615073 ],
       [5.617813 ],
       [5.610145 ],
       [5.6058064],
       [5.607363 ],
       [5.6110573],
       [5.622455 ],
       [5.6162434],
       [5.6122127],
       [5.5999107],
       [5.611806 ],
       [5.5991592],
       [5.5916357],
       [5.603983 ],
       [5.6173816],
       [5.6115456],
       [5.6045036],
       [5.6137724],
       [5.613589 ],
       [5.6043477],
       [5.61176  ],
       [5.6102176],
       [5.6130223],
       [5.6176605],
       [5.618403 ],
       [5.617872 ],
       [5.6099377],
       [5.611784 ],
       [5.616594 ],
       [5.610095 ],
       [5.576234 ],
       [5.6017756],
       [5.608303 ],
       [5.6147966],
       [5.616707 ],
       [5.6106505],
       [5.6031876],
       [5.6132736],
       [5.6080775],
       [5.6157084],
       [5.6144094],
       [5.5848475],
       [5.6084385],
       [5.6064773],
       [5.611321 ],
       [5.608117 ],
       [5.616254 ],
       [5.60621  ],
       [5.6127644],
       [5.6147246],
       [5.6178055],
       [5.6151485],
       [5.6092644],
       [5.5998487],
       [5.6038213],
       [5.6013193],
       [5.616211 ],
       [5.622737 ],
       [5.6191316],
       [5.6174946],
       [5.60668  ],
       [5.62222  ],
       [5.6052666],
       [5.6168194],
       [5.609423 ],
       [5.614213 ],
       [5.605143 ],
       [5.612207 ],
       [5.607274 ],
       [5.6076756]], dtype=float32)

None

## Classification using tf.Keras

In this exercise, we will build a Deep Neural Network using tf.Keras. We will use Iris Dataset for this exercise.

### Load the given Iris data using pandas (Iris.csv)

In [0]:
data_iris = pd.read_csv('/content/drive/My Drive/lab_residency6/11_Iris.csv')

In [263]:
data_iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

### Target set has different categories. So, Label encode them. And convert into one-hot vectors using get_dummies in pandas.

In [0]:
data_iris= data_iris.drop(['Id'], axis=1)

In [0]:
data_iris= pd.get_dummies(data=data_iris, columns=['Species'])

In [266]:
data_iris.head()

   SepalLengthCm  SepalWidthCm  ...  Species_Iris-versicolor  Species_Iris-virginica
0            5.1           3.5  ...                        0                       0
1            4.9           3.0  ...                        0                       0
2            4.7           3.2  ...                        0                       0
3            4.6           3.1  ...                        0                       0
4            5.0           3.6  ...                        0                       0

[5 rows x 7 columns]

### Splitting the data into feature set and target set

In [0]:
X = data_iris[['SepalLengthCm',	'SepalWidthCm',	'PetalLengthCm',	'PetalWidthCm']]

In [0]:
y = data_iris[['Species_Iris-setosa', 'Species_Iris-versicolor',	'Species_Iris-virginica', ]]

In [0]:
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=7)

###  Building Model in tf.keras

Build a Linear Classifier model  <br>
1.  Use Dense Layer  with input shape of 4 (according to the feature set) and number of outputs set to 3<br> 
2. Apply Softmax on Dense Layer outputs <br>
3. Use SGD as Optimizer
4. Use categorical_crossentropy as loss function

In [0]:
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers.core import Dense,Dropout,Activation,Flatten
from keras.layers.convolutional import Conv2D,MaxPooling2D
from keras.utils import np_utils

In [0]:
# create model
model = Sequential()
model.add(Dense(12,input_dim=4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(3, activation='softmax'))
# Compile model
model.compile(loss='binary_crossentropy', optimizer='sgd', metrics=['accuracy'])

### Model Training

In [279]:
# Fit the model
model.fit(x_train, y_train, validation_data=(x_test,y_test), epochs=10, batch_size=5)

Train on 105 samples, validate on 45 samples
Epoch 1/10
105/105 [==============================] - 0s 3ms/step - loss: 0.7558 - acc: 0.7302 - val_loss: 0.4726 - val_acc: 0.7556
Epoch 2/10
105/105 [==============================] - 0s 894us/step - loss: 0.4292 - acc: 0.8381 - val_loss: 0.4190 - val_acc: 0.8741
Epoch 3/10
105/105 [==============================] - 0s 774us/step - loss: 0.3890 - acc: 0.8825 - val_loss: 0.3930 - val_acc: 0.8444
Epoch 4/10
105/105 [==============================] - 0s 795us/step - loss: 0.3608 - acc: 0.8667 - val_loss: 0.3668 - val_acc: 0.8444
Epoch 5/10
105/105 [==============================] - 0s 838us/step - loss: 0.3375 - acc: 0.8730 - val_loss: 0.3503 - val_acc: 0.8593
Epoch 6/10
105/105 [==============================] - 0s 821us/step - loss: 0.3156 - acc: 0.8825 - val_loss: 0.3371 - val_acc: 0.8148
Epoch 7/10
105/105 [==============================] - 0s 805us/step - loss: 0.3026 - acc: 0.8730 - val_loss: 0.3100 - val_acc: 0.8741
Epoch 8/10
105/105 [==============================] - 0s 785us/step - loss: 0.2865 - acc: 0.8889 - val_loss: 0.2947 - val_acc: 0.9185
Epoch 9/10
105/105 [==============================] - 0s 862us/step - loss: 0.2696 - acc: 0.9206 - val_loss: 0.2840 - val_acc: 0.8593
Epoch 10/10
105/105 [==============================] - 0s 805us/step - loss: 0.2600 - acc: 0.9206 - val_loss: 0.2713 - val_acc: 0.9111

### Model Prediction

In [0]:
y_predict=model.predict_classes(x_test)

In [281]:
y_predict

array([2, 2, 0, 2, 2, 0, 1, 1, 0, 1, 2, 1, 0, 2, 0, 2, 2, 2, 0, 0, 1, 2,
       2, 2, 2, 2, 1, 1, 2, 2, 2, 1, 0, 2, 1, 0, 0, 0, 0, 2, 2, 1, 2, 2,
       1])

### Save the Model

In [0]:
from keras.models import load_model

model.save('/content/drive/My Drive/lab_residency6/iris_pred_keras.h5')

### Build and Train a Deep Neural network with 2 hidden layer  - Optional - For Practice

Does it perform better than Linear Classifier? What could be the reason for difference in performance?